spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: Manas@65
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: USER-SERVICE


  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-with-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
server:
  port: 8081


