spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: Manas@65
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: USER-SERVICE


  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-with-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
server:
  port: 8081
# Application Properties
app:
  expirationTime: 604800000
  jwt-secret: e58b1787cf04010493fe722e9129e1e4c9876b91ddb67683dcf28d87d467cc1a
  TWILIO_ACCOUNT_SID: AC031f4ab40c9dd7522b3d742ce919358c
  TWILIO_AUTH_TOKEN: eee90560bb8bf550c48b56c1eb9570d9

